# Useful Applications

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf
import datetime as dt
import math

from jupyterthemes import jtplot
jtplot.style(theme='onedork', figsize=(15, 9))

## Class

In [28]:
class UsefulApplications():
    def __init__(self, ticker, start, end):
        self.ticker = ticker
        self.start = start
        self.end = end
        self.get_data()
    
    def get_data(self):
        data = yf.download(self.ticker, self.start, self.end, interval='1d', auto_adjust=False, progress=False)
        data['returns'] = np.log(data['Close'].div(data['Close'].shift(1)))
        data.dropna(inplace=True)
        self.asset = data
        return data
        
    def amihud_illiquidity(self):
#         close      = np.array(ibm_df['Close'])
#         dollar_vol = np.array(ibm_df['Volume'] * close)
#         returns    = np.array((close[1:] - close[:-1]) / close[1:])
#         illiq      = np.mean(np.divide(np.abs(returns), dollar_vol[1:]))
        
        data = self.asset.copy()
        dollar_vol = data['Volume'] * data['Close']
        illiq      = np.mean(np.divide(np.abs(data['returns']), dollar_vol[1:]))
        self.print_msg(f'Aminud\'s illiquidity  for {self.ticker} is {illiq}')
    
    def rolls_spread(self):
        data = self.asset.copy()
        data['Diff'] = data['Close'].diff()
        data_cov     = np.cov(data['Diff'][1:-1], data['Diff'][2:])
        
        if data_cov[0, 1] < 0:
            self.print_msg(f'Roll\'s Spread for {self.ticker}: {round(2*np.sqrt(-data_cov[0,1]), 5)}')
        else:
            self.print_msg(f'Roll\'s Spread for {self.ticker}: {round(2*np.sqrt(data_cov[0,1]), 5)}')
    
    def print_msg(self, msg):
        print(len(msg)*'*')
        print(msg)
#         print(len(msg)*'*')
    
    def summary(self):
        pass
    


In [32]:
u_app = UsefulApplications('IBM', dt.datetime(2013, 10, 1), dt.datetime(2013, 10, 30))
u_app.rolls_spread()
u_app.amihud_illiquidity()

******************************
Roll's Spread for IBM: 1.01175
*******************************************************
Aminud's illiquidity  for IBM is 1.1600426194329588e-11


In [ ]:
def rolls_spread(ticker, start=dt.datetime(2002, 1, 1), end=dt.datetime(2022, 12, 31), interval='1d', adjustment=False):
    asset               = yf.download(ticker, start, end, interval, auto_adjust=adjustment, progress=False)
    asset_close         = asset['Close'].to_frame()
    asset_close['Diff'] = asset_close['Close'].diff()
    asset_close_cov     = np.cov(asset_close['Diff'][1:-1], asset_close['Diff'][2:])

    if asset_close_cov[0, 1] < 0:
        print(f'Roll\'s Spread for {ticker}: {round(2*np.sqrt(-asset_close_cov[0,1]), 3)}')
    else:
        print(f'Roll\'s Spread for {ticker}: {round(2*np.sqrt(asset_close_cov[0,1]), 3)}')

## Roll's model to estimate spread (1984)

- __[Trading costs - The Roll Spread Estimator](https://ba-odegaard.no/teach/notes/liquidity_estimators/roll_spread_estimator/roll_lectures.pdf)__
- __[A Simple Implicit Measure of the Effective Bid-Ask Spread in an Efficient Market](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1540-6261.1984.tb03897.x)__

In [22]:
rolls_spread('AAPL', adjustment=True)

Roll's Spread for AAPL: 0.512


### Research

In [2]:
df = pd.read_csv('../../data/IBM_2013-09-01_2013-11-11_1d.csv', index_col=0, parse_dates=True)
df.head()

Open        High         Low       Close   Volume  \
Date                                                                  
2013-09-03  117.398367  117.839496  116.682332  117.609344  3647611   
2013-09-04  117.366468  117.756444  116.554525  117.078766  2717403   
2013-09-05  117.219388  118.274267  117.040379  117.730843  2999510   
2013-09-06  118.050496  118.267872  116.771854  117.014801  3037061   
2013-09-09  117.430359  118.587533  117.193810  118.261475  3155991   

            Dividends  Stock Splits  
Date                                 
2013-09-03        0.0           0.0  
2013-09-04        0.0           0.0  
2013-09-05        0.0           0.0  
2013-09-06        0.0           0.0  
2013-09-09        0.0           0.0

In [3]:
close = df['Close'].to_frame()
close.head()

Close
Date                  
2013-09-03  117.609344
2013-09-04  117.078766
2013-09-05  117.730843
2013-09-06  117.014801
2013-09-09  118.261475

In [4]:
close['Diff'] = df['Close'].diff()
close.head()

Close      Diff
Date                            
2013-09-03  117.609344       NaN
2013-09-04  117.078766 -0.530579
2013-09-05  117.730843  0.652077
2013-09-06  117.014801 -0.716042
2013-09-09  118.261475  1.246674

In [5]:
_cov = np.cov(close['Diff'][1:-1], close['Diff'][2:])
_cov[0, 1]

-0.14103707800980902

In [6]:
np.corrcoef(close['Diff'][1:-1], close['Diff'][2:])[0,1]

-0.05134942727349844

In [7]:
if _cov[0, 1] < 0:
    print(f'Roll\'s Spread for IBM: {round(2*np.sqrt(-_cov[0,1]), 3)}')
else:
    print(f'Roll\'s Spread for IBM: {round(2*np.sqrt(_cov[0,1]), 3)}')

Roll's Spread for IBM: 0.751


In [8]:
ibm_wo_adjustment = yf.download('IBM', dt.datetime(2013, 9, 11), dt.datetime(2013, 11, 11), '1d')

[*********************100%***********************]  1 of 1 completed


In [10]:
ibm_wo_adj_close = ibm_wo_adjustment['Close'].to_frame()
ibm_wo_adj_close['Diff'] = ibm_wo_adj_close['Close'].diff()
ibm_wo_adj_close.head()

Close      Diff
Date                            
2013-09-11  182.313583       NaN
2013-09-12  182.342255  0.028671
2013-09-13  183.718933  1.376678
2013-09-16  184.655838  0.936905
2013-09-17  183.709366 -0.946472

In [12]:
_ibm_wo_adj_cov = np.cov(ibm_wo_adj_close['Diff'][1:-1], ibm_wo_adj_close['Diff'][2:])
_ibm_wo_adj_cov[0, 1]

-0.5197988161154193

In [13]:
if _ibm_wo_adj_cov[0, 1] < 0:
    print(f'Roll\'s Spread for IBM(no adjustment): {round(2*np.sqrt(-_ibm_wo_adj_cov[0,1]), 3)}')
else:
    print(f'Roll\'s Spread for IBM(no adjustment): {round(2*np.sqrt(_ibm_wo_adj_cov[0,1]), 3)}')

Roll's Spread for IBM(no adjustment): 1.442


## Amihud's model for illiquidity (2002)

- __[Amihud Illiquidity Measure](https://breakingdownfinance.com/finance-topics/alternative-investments/amihud-illiquidity-measure/)__
- __[ILLIQUIDITY AND STOCK RETURNS: Cross-Section and Time-Series Effects](https://deliverypdf.ssrn.com/delivery.php?ID=996103073088116024117083087064091068036022029078044001090016109113126101021095072012074014095026118068068048028116102114123091093097081107024117113108069091098068086072104076008064076097125&EXT=pdf&INDEX=TRUE)__
- __[The Night and Day of Amihud’s (2002) Liquidity Measure](https://www.chapman.edu/business/_files/faculty-research/2019-conference-money-finance/yashar-barardehi-paper.pdf)__
- __[Price Impact or Trading Volume: Why is the Amihud (2002) Illiquidity Measure Priced?](https://www.lehigh.edu/~jms408/Lu_2014.pdf)__
- __[Illiquidity: A study on how investing in illiquid assets can be profitable](http://arno.uvt.nl/show.cgi?fid=142126)__
- __[An Analysis of the Amihud Illiquidity Premium](https://www.researchgate.net/publication/228315879_An_Analysis_of_the_Amihud_Illiquidity_Premium)__
- __[Illiquidity and Stock Returns: Empirical Evidence from the Stockholm Stock Exchange](http://arc.hhs.se/download.aspx?MediumId=1481)__

In [2]:
ibm_df = yf.download('IBM', dt.datetime(2013, 10, 1), dt.datetime(2013, 10, 30), '1d', auto_adjust=True)
ibm_df

[*********************100%***********************]  1 of 1 completed


Open        High         Low       Close    Volume  \
Date                                                                   
2013-10-01  118.491640  119.329143  118.050501  119.156532   2804535   
2013-10-02  118.619475  119.111757  117.897043  118.248672   3783487   
2013-10-03  118.082451  118.248675  116.995604  117.545425   3359543   
2013-10-04  117.743620  118.357370  117.366429  117.698875   2995326   
2013-10-07  116.260399  117.193809  116.260399  116.362694   4148854   
2013-10-08  116.285959  116.349897  114.252925  114.259323   5834902   
2013-10-09  114.674844  116.145280  114.502223  115.921516   4626981   
2013-10-10  117.104278  118.127197  116.586435  118.127197   3827209   
2013-10-11  118.434134  119.060659  117.711701  119.015915   3381300   
2013-10-14  118.536376  119.546500  117.903453  119.533714   2785603   
2013-10-15  118.747348  118.875215  117.775581  118.056885   3519895   
2013-10-16  118.542792  119.380295  118.267886  119.380295   7027028   
2013-10-17  111.139459  113.159718  110.327527  111.772392  23397869   
2013-10-18  111.753204  111.881070  110.762263  111.101097  11033208   
2013-10-21  111.510263  111.721230  110.365874  110.512924   7425240   
2013-10-22  110.826190  112.245484  110.570457  111.861885   7298256   
2013-10-23  111.938598  112.513981  111.497469  112.373329   5658232   
2013-10-24  112.795272  113.728683  112.680192  113.671143   5787832   
2013-10-25  114.073906  114.502249  112.686581  113.063782   5065569   
2013-10-28  113.185307  113.728731  112.648281  113.383499   3883484   
2013-10-29  113.556106  116.560918  113.479392  116.433052   9314212   

            Dividends  Stock Splits  
Date                                 
2013-10-01        0.0           0.0  
2013-10-02        0.0           0.0  
2013-10-03        0.0           0.0  
2013-10-04        0.0           0.0  
2013-10-07        0.0           0.0  
2013-10-08        0.0           0.0  
2013-10-09        0.0           0.0  
2013-10-10        0.0           0.0  
2013-10-11        0.0           0.0  
2013-10-14        0.0           0.0  
2013-10-15        0.0           0.0  
2013-10-16        0.0           0.0  
2013-10-17        0.0           0.0  
2013-10-18        0.0           0.0  
2013-10-21        0.0           0.0  
2013-10-22        0.0           0.0  
2013-10-23        0.0           0.0  
2013-10-24        0.0           0.0  
2013-10-25        0.0           0.0  
2013-10-28        0.0           0.0  
2013-10-29        0.0           0.0

In [7]:
close      = np.array(ibm_df['Close'])
dollar_vol = np.array(ibm_df['Volume'] * close)
returns    = np.array((close[1:] - close[:-1]) / close[1:])
illiq      = np.mean(np.divide(np.abs(returns), dollar_vol[1:]))
print(f'Aminud\'s illiquidity is {illiq}')

Aminud's illiquidity is 1.7349160136434808e-11


In [9]:
close[1:], close[:-1], close

(array([118.24867249, 117.54542542, 117.69887543, 116.36269379,
        114.25932312, 115.92151642, 118.12719727, 119.01591492,
        119.53371429, 118.05688477, 119.3802948 , 111.77239227,
        111.10109711, 110.51292419, 111.86188507, 112.37332916,
        113.67114258, 113.06378174, 113.38349915, 116.43305206]),
 array([119.15653229, 118.24867249, 117.54542542, 117.69887543,
        116.36269379, 114.25932312, 115.92151642, 118.12719727,
        119.01591492, 119.53371429, 118.05688477, 119.3802948 ,
        111.77239227, 111.10109711, 110.51292419, 111.86188507,
        112.37332916, 113.67114258, 113.06378174, 113.38349915]),
 array([119.15653229, 118.24867249, 117.54542542, 117.69887543,
        116.36269379, 114.25932312, 115.92151642, 118.12719727,
        119.01591492, 119.53371429, 118.05688477, 119.3802948 ,
        111.77239227, 111.10109711, 110.51292419, 111.86188507,
        112.37332916, 113.67114258, 113.06378174, 113.38349915,
        116.43305206]))